package app.line.ui

/** One piece of an icon on a 24x24 grid: an outline (2-unit round-capped stroke), or a solid shape when [fill]. */
data class IconShape(val d: String, val fill: Boolean = false)

/** Generated by tools/icons/build_icon_paths.py from tools/icons/*.svg; edit the SVGs, not this file. */
object IconPaths {
    val all: Map<String, List<IconShape>> = mapOf(
        "alert" to listOf(
            IconShape("M3 12a9 9 0 1 0 18 0 9 9 0 1 0-18 0z"),
            IconShape("M12 7.5v5"),
            IconShape("M10.75 16.5a1.25 1.25 0 1 0 2.5 0 1.25 1.25 0 1 0-2.5 0z", true),
        ),
        "attach" to listOf(
            IconShape("M19.24 9.59l-6.43 7.66A4 4 0 0 1 6.69 12.11l5.79-6.89a2 2 0 0 1 3.06 2.57l-5.14 6.13"),
        ),
        "back" to listOf(
            IconShape("M14.5 5.5L8 12l6.5 6.5"),
        ),
        "backspace" to listOf(
            IconShape("M8.5 5.5h10A2.5 2.5 0 0 1 21 8v8a2.5 2.5 0 0 1-2.5 2.5H8.5L3 12z"),
            IconShape("M12 9.5l5 5m0-5l-5 5"),
        ),
        "battery" to listOf(
            IconShape("M5.5 7h11A2.5 2.5 0 0 1 19 9.5v5A2.5 2.5 0 0 1 16.5 17H5.5A2.5 2.5 0 0 1 3 14.5v-5A2.5 2.5 0 0 1 5.5 7z"),
            IconShape("M21 10.5v3"),
            IconShape("M7 10h5a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1H7A1 1 0 0 1 6 13V11a1 1 0 0 1 1-1z", true),
        ),
        "bell" to listOf(
            IconShape("M6.5 11a5.5 5.5 0 0 1 11 0v4.5l2 2H4.5l2-2z"),
            IconShape("M10 19.8a2.5 2.5 0 0 0 4 0"),
        ),
        "bell_off" to listOf(
            IconShape("M6.5 11a5.5 5.5 0 0 1 .01-.25m3.58-4.9A5.5 5.5 0 0 1 17.5 11v2.26M13.26 17.5H4.5l2-2V11"),
            IconShape("M10 19.8a2.5 2.5 0 0 0 4 0"),
            IconShape("M4 4L20 20"),
        ),
        "camera" to listOf(
            IconShape("M9 7l1.5-2.5h3L15 7h3a3 3 0 0 1 3 3v7a3 3 0 0 1-3 3H6A3 3 0 0 1 3 17V10A3 3 0 0 1 6 7z"),
            IconShape("M8.5 13a3.5 3.5 0 1 0 7 0 3.5 3.5 0 1 0-7 0z"),
        ),
        "chat" to listOf(
            IconShape("M7 4H17a4 4 0 0 1 4 4v5a4 4 0 0 1-4 4H12.5L8 20.5V17H7A4 4 0 0 1 3 13V8A4 4 0 0 1 7 4z"),
        ),
        "check" to listOf(
            IconShape("M4.5 12l5 5 10-10"),
        ),
        "check_double" to listOf(
            IconShape("M3 12.5l4 4 9-9"),
            IconShape("M21 9.5l-7 7-1-1"),
        ),
        "chevron_down" to listOf(
            IconShape("M5.5 9.5L12 16l6.5-6.5"),
        ),
        "chevron_left" to listOf(
            IconShape("M14.5 5.5L8 12l6.5 6.5"),
        ),
        "chevron_right" to listOf(
            IconShape("M9.5 5.5L16 12 9.5 18.5"),
        ),
        "clock" to listOf(
            IconShape("M3 12a9 9 0 1 0 18 0 9 9 0 1 0-18 0z"),
            IconShape("M12 7.5V12l3.5 2.5"),
        ),
        "close" to listOf(
            IconShape("M6 6L18 18M18 6L6 18"),
        ),
        "compose" to listOf(
            IconShape("M11 3H6A3 3 0 0 0 3 6V18a3 3 0 0 0 3 3H18a3 3 0 0 0 3-3V12"),
            IconShape("M8.41 15.93l2.98-.5 8.05-8.05a.8 .8 0 0 0 0-1.13l-1.7-1.7a.8 .8 0 0 0-1.13 0L8.57 12.61l-.5 2.98a.3 .3 0 0 0 .35 .35z"),
        ),
        "copy" to listOf(
            IconShape("M11.5 9h7A2.5 2.5 0 0 1 21 11.5v7A2.5 2.5 0 0 1 18.5 21h-7A2.5 2.5 0 0 1 9 18.5v-7A2.5 2.5 0 0 1 11.5 9z"),
            IconShape("M6 15H5.5A2.5 2.5 0 0 1 3 12.5v-7A2.5 2.5 0 0 1 5.5 3h7A2.5 2.5 0 0 1 15 5.5V6"),
        ),
        "download" to listOf(
            IconShape("M12 4V15M7.5 10.5L12 15l4.5-4.5"),
            IconShape("M4 15.5V18a3 3 0 0 0 3 3H17a3 3 0 0 0 3-3V15.5"),
        ),
        "edit" to listOf(
            IconShape("M4.23 20.12l3.89-.7L20.2 7.33a.8 .8 0 0 0 0-1.13L17.8 3.8a.8 .8 0 0 0-1.13 0L4.58 15.89l-.7 3.89a.3 .3 0 0 0 .35 .35z"),
            IconShape("M18.22 9.31L14.69 5.78"),
        ),
        "file" to listOf(
            IconShape("M7 3h6l6 6V19a2 2 0 0 1-2 2H7A2 2 0 0 1 5 19V5A2 2 0 0 1 7 3z"),
            IconShape("M13 3V7a2 2 0 0 0 2 2h4"),
        ),
        "forward" to listOf(
            IconShape("M9.5 5.5L16 12 9.5 18.5"),
        ),
        "globe" to listOf(
            IconShape("M3 12a9 9 0 1 0 18 0 9 9 0 1 0-18 0z"),
            IconShape("M3 12H21"),
            IconShape("M12 3a4.5 9 0 0 1 0 18A4.5 9 0 0 1 12 3z"),
        ),
        "image" to listOf(
            IconShape("M6 4H18a3 3 0 0 1 3 3V17a3 3 0 0 1-3 3H6A3 3 0 0 1 3 17V7A3 3 0 0 1 6 4z"),
            IconShape("M6.75 9.5a1.75 1.75 0 1 0 3.5 0 1.75 1.75 0 1 0-3.5 0z", true),
            IconShape("M3 15.5l5-5 5 5 3-3L21 17"),
        ),
        "info" to listOf(
            IconShape("M3 12a9 9 0 1 0 18 0 9 9 0 1 0-18 0z"),
            IconShape("M10.75 7.75a1.25 1.25 0 1 0 2.5 0 1.25 1.25 0 1 0-2.5 0z", true),
            IconShape("M12 11.25V16.5"),
        ),
        "key" to listOf(
            IconShape("M4 16a4 4 0 1 0 8 0 4 4 0 1 0-8 0z"),
            IconShape("M11 13l9-9"),
            IconShape("M16 8l2.5 2.5"),
            IconShape("M18.5 5.5l2 2"),
        ),
        "keypad" to listOf(
            IconShape("M4.4 6A1.6 1.6 0 1 1 7.6 6 1.6 1.6 0 1 1 4.4 6zm6 0a1.6 1.6 0 1 1 3.2 0A1.6 1.6 0 1 1 10.4 6zm6 0a1.6 1.6 0 1 1 3.2 0A1.6 1.6 0 1 1 16.4 6zm-12 6a1.6 1.6 0 1 1 3.2 0A1.6 1.6 0 1 1 4.4 12zm6 0a1.6 1.6 0 1 1 3.2 0 1.6 1.6 0 1 1-3.2 0zm6 0a1.6 1.6 0 1 1 3.2 0 1.6 1.6 0 1 1-3.2 0zm-12 6a1.6 1.6 0 1 1 3.2 0A1.6 1.6 0 1 1 4.4 18zm6 0a1.6 1.6 0 1 1 3.2 0 1.6 1.6 0 1 1-3.2 0zm6 0a1.6 1.6 0 1 1 3.2 0 1.6 1.6 0 1 1-3.2 0z", true),
        ),
        "link" to listOf(
            IconShape("M8.82 10.94L5.28 14.47a3 3 0 0 0 4.24 4.24l3.54-3.54"),
            IconShape("M10.94 8.82l3.54-3.54a3 3 0 1 0 4.24 4.24l-3.54 3.54"),
            IconShape("M9.88 14.12l4.24-4.24"),
        ),
        "lock" to listOf(
            IconShape("M7.5 10.5h9A2.5 2.5 0 0 1 19 13v5.5A2.5 2.5 0 0 1 16.5 21h-9A2.5 2.5 0 0 1 5 18.5V13a2.5 2.5 0 0 1 2.5-2.5z"),
            IconShape("M8 10.5v-3a4 4 0 0 1 8 0v3"),
            IconShape("M12 14.5V17"),
        ),
        "mic" to listOf(
            IconShape("M9 6a3 3 0 0 1 6 0v6A3 3 0 0 1 9 12z"),
            IconShape("M5.5 11a6.5 6.5 0 0 0 13 0"),
            IconShape("M12 17.5V21"),
        ),
        "mic_off" to listOf(
            IconShape("M9.19 4.95A3 3 0 0 1 15 6v4.76M5.5 11a6.5 6.5 0 0 0 7.65 6.4m4.77-3.72A6.5 6.5 0 0 0 18.5 11M12 17.5V21"),
            IconShape("M4 4L20 20"),
        ),
        "more_vertical" to listOf(
            IconShape("M10.25 5a1.75 1.75 0 1 0 3.5 0 1.75 1.75 0 1 0-3.5 0z", true),
            IconShape("M10.25 12a1.75 1.75 0 1 0 3.5 0 1.75 1.75 0 1 0-3.5 0z", true),
            IconShape("M10.25 19a1.75 1.75 0 1 0 3.5 0 1.75 1.75 0 1 0-3.5 0z", true),
        ),
        "pause" to listOf(
            IconShape("M8 4.5H9A1.5 1.5 0 0 1 10.5 6V18A1.5 1.5 0 0 1 9 19.5H8A1.5 1.5 0 0 1 6.5 18V6A1.5 1.5 0 0 1 8 4.5zm7 0h1A1.5 1.5 0 0 1 17.5 6V18A1.5 1.5 0 0 1 16 19.5H15A1.5 1.5 0 0 1 13.5 18V6A1.5 1.5 0 0 1 15 4.5z", true),
        ),
        "person" to listOf(
            IconShape("M8.25 7.75a3.75 3.75 0 1 0 7.5 0 3.75 3.75 0 1 0-7.5 0z"),
            IconShape("M5 20.5V19a4.5 4.5 0 0 1 4.5-4.5h5A4.5 4.5 0 0 1 19 19v1.5"),
        ),
        "phone" to listOf(
            IconShape("M19.34 16.68l-2.47 2.47C12.13 22.47 1.53 11.87 4.85 7.13L7.32 4.66a1.5 1.5 0 0 1 2.12 0l1.41 1.41a1.5 1.5 0 0 1 0 2.12l-1.7 1.7c-1.34 1.48 3.46 6.29 4.95 4.95l1.7-1.7a1.5 1.5 0 0 1 2.12 0l1.41 1.41a1.5 1.5 0 0 1 0 2.12z"),
        ),
        "phone_end" to listOf(
            IconShape("M3.07 15.79V12.12c1.05-5.99 16.8-5.99 17.85 0v3.68a1.58 1.58 0 0 1-1.57 1.58h-2.1a1.58 1.58 0 0 1-1.57-1.58V13.27c-.11-2.1-7.25-2.1-7.35 0v2.52A1.58 1.58 0 0 1 6.75 17.37H4.65A1.58 1.58 0 0 1 3.07 15.79z"),
        ),
        "phone_incoming" to listOf(
            IconShape("M14.89 17.77l-1.78 1.78c-3.41 2.39-11.05-5.24-8.65-8.65L6.23 9.11a1.08 1.08 0 0 1 1.53 0l1.02 1.02a1.08 1.08 0 0 1 0 1.53L7.56 12.88c-.97 1.07 2.49 4.53 3.56 3.56l1.22-1.22a1.08 1.08 0 0 1 1.53 0l1.02 1.02a1.08 1.08 0 0 1 0 1.53z"),
            IconShape("M14 5v5h5"),
            IconShape("M14 10l7-7"),
        ),
        "phone_missed" to listOf(
            IconShape("M14.89 17.77l-1.78 1.78c-3.41 2.39-11.05-5.24-8.65-8.65L6.23 9.11a1.08 1.08 0 0 1 1.53 0l1.02 1.02a1.08 1.08 0 0 1 0 1.53L7.56 12.88c-.97 1.07 2.49 4.53 3.56 3.56l1.22-1.22a1.08 1.08 0 0 1 1.53 0l1.02 1.02a1.08 1.08 0 0 1 0 1.53z"),
            IconShape("M15 4l5 5"),
            IconShape("M20 4L15 9"),
        ),
        "phone_outgoing" to listOf(
            IconShape("M14.89 17.77l-1.78 1.78c-3.41 2.39-11.05-5.24-8.65-8.65L6.23 9.11a1.08 1.08 0 0 1 1.53 0l1.02 1.02a1.08 1.08 0 0 1 0 1.53L7.56 12.88c-.97 1.07 2.49 4.53 3.56 3.56l1.22-1.22a1.08 1.08 0 0 1 1.53 0l1.02 1.02a1.08 1.08 0 0 1 0 1.53z"),
            IconShape("M16 3h5V8"),
            IconShape("M21 3l-7 7"),
        ),
        "play" to listOf(
            IconShape("M6.5 8.31v7.38A2.2 2.2 0 0 0 9.8 17.6l6.4-3.69a2.2 2.2 0 0 0 0-3.81L9.8 6.4A2.2 2.2 0 0 0 6.5 8.31z", true),
        ),
        "plus" to listOf(
            IconShape("M12 5V19M5 12H19"),
        ),
        "refresh" to listOf(
            IconShape("M18.62 16.02a7.5 7.5 0 1 1-1.6-9.09"),
            IconShape("M16.82 2.63l.2 4.3-4.3 .2"),
        ),
        "search" to listOf(
            IconShape("M4 10.5a6.5 6.5 0 1 0 13 0 6.5 6.5 0 1 0-13 0z"),
            IconShape("M15.5 15.5L20 20"),
        ),
        "send" to listOf(
            IconShape("M4.67 10.02l14.5-5.97a.6 .6 0 0 1 .78 .78l-5.97 14.5A.6 .6 0 0 1 12.9 19.38l-2.81-5.23A.6 .6 0 0 0 9.84 13.91L4.62 11.1a.6 .6 0 0 1 .06-1.08z"),
            IconShape("M20.5 3.5L10 14"),
        ),
        "settings" to listOf(
            IconShape("M13.5 6.5a2.5 2.5 0 1 0 5 0 2.5 2.5 0 1 0-5 0z"),
            IconShape("M3.5 6.5h6.8"),
            IconShape("M5.5 12a2.5 2.5 0 1 0 5 0 2.5 2.5 0 1 0-5 0z"),
            IconShape("M13.7 12h6.8"),
            IconShape("M11.5 17.5a2.5 2.5 0 1 0 5 0 2.5 2.5 0 1 0-5 0z"),
            IconShape("M3.5 17.5H8.3"),
        ),
        "share" to listOf(
            IconShape("M12 14.5V3.5M8.5 7L12 3.5 15.5 7"),
            IconShape("M8.5 10H7A2.5 2.5 0 0 0 4.5 12.5v6A2.5 2.5 0 0 0 7 21H17a2.5 2.5 0 0 0 2.5-2.5v-6A2.5 2.5 0 0 0 17 10H15.5"),
        ),
        "shield_check" to listOf(
            IconShape("M12 3l7.5 3v5.5c0 4.5-3 7.7-7.5 9.5-4.5-1.8-7.5-5-7.5-9.5V6z"),
            IconShape("M8.7 11.8L11 14.2l4.5-4.8"),
        ),
        "sound_wave" to listOf(
            IconShape("M6 9v6M12 4.5v15M18 9v6"),
        ),
        "speaker" to listOf(
            IconShape("M3.5 9.5h4l4.5-4v13l-4.5-4h-4z"),
            IconShape("M15.34 8.99a4.5 4.5 0 0 1 0 6.02"),
            IconShape("M18.32 6.31a8.5 8.5 0 0 1 0 11.38"),
        ),
        "speaker_off" to listOf(
            IconShape("M3.5 9.5h4l4.5-4v13l-4.5-4h-4z"),
            IconShape("M16 9.5l5 5m0-5l-5 5"),
        ),
        "stop" to listOf(
            IconShape("M8.5 5.5h7a3 3 0 0 1 3 3v7a3 3 0 0 1-3 3h-7a3 3 0 0 1-3-3v-7a3 3 0 0 1 3-3z", true),
        ),
        "trash" to listOf(
            IconShape("M4 6.5H20"),
            IconShape("M9 6.5V5a1.5 1.5 0 0 1 1.5-1.5h3A1.5 1.5 0 0 1 15 5V6.5"),
            IconShape("M6 6.5V18a3 3 0 0 0 3 3h6a3 3 0 0 0 3-3V6.5"),
            IconShape("M10 10.5v6m4-6v6"),
        ),
        "users" to listOf(
            IconShape("M5.5 8a3.5 3.5 0 1 0 7 0 3.5 3.5 0 1 0-7 0z"),
            IconShape("M3 20.5V19a4 4 0 0 1 4-4h4a4 4 0 0 1 4 4v1.5"),
            IconShape("M15.5 4.6a3.4 3.4 0 0 1 0 6.8"),
            IconShape("M17.5 15.2A3.5 3.5 0 0 1 21 18.7v1.8"),
        ),
        "volume" to listOf(
            IconShape("M3.5 9.5h4l4.5-4v13l-4.5-4h-4z"),
            IconShape("M15.34 8.99a4.5 4.5 0 0 1 0 6.02"),
            IconShape("M18.32 6.31a8.5 8.5 0 0 1 0 11.38"),
        ),
        "waveform" to listOf(
            IconShape("M4 10.5v3M8 7V17M12 4V20M16 8v8m4-5.5v3"),
        ),
        "wifi_off" to listOf(
            IconShape("M8.82 14.32a4.5 4.5 0 0 1 .69-.57M5.64 11.14a9 9 0 0 1 .66-.6m6.48-2a9 9 0 0 1 5.59 2.6M2.45 7.95A13.5 13.5 0 0 1 3.1 7.35M8.66 4.42A13.5 13.5 0 0 1 21.55 7.95"),
            IconShape("M10.6 17.5a1.4 1.4 0 1 0 2.8 0 1.4 1.4 0 1 0-2.8 0z", true),
            IconShape("M4 4L20 20"),
        ),
    )

    fun get(name: String): List<IconShape>? = all[name]
}
